name: Assertions

on:
  pull_request:
    branches: [main, develop]

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ github.token }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Update NPM
        run: npm i -g npm@latest

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-

      - name: Install dependencies
        run: npm i --legacy-peer-deps

      - name: Lint scripts
        run: npx eslint '**/*.{js,ts,jsx,tsx}'

      - name: Lint styles
        run: npx stylelint '**/*.{css,scss}'

      - name: Lint markdown
        run: npx markdownlint '**/*.md'
